# -*- coding: utf-8 -*-
"""Spotify_Songs_Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uN5zoYVBf9r80DgdpKjxNfxNJxwW5j8h
"""

import pandas as pd
import io
import csv

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('data (1).csv')

df

df2 = pd.read_csv('top10s copy.txt')

df2





